### PR TITLE
itIT locales update

### PR DESCRIPTION
**Pull request by simoflorence**
Just finished to update itIT locales for BW. Feel free to add it in next releases.

### CODE REVIEW

**Comment by funkydude** [comment]
@simoflorence Thanks for your work on this.

With regards to this line:
`L.yourPowerTest = "Tuo Potere: %d" -- Tuo Potere: 42`

Is this based on the players gender? If so, we can fix it to adapt.

**Comment by simoflorence** [comment]
Should be genderless in this contest (and this translation IS genderless)

**Comment by funkydude** [comment]
@simoflorence Thanks for clarifying.

I asked because you also have this:
`L.yourAltPower = "Tuo %s: %d" -- esempio: Tua Corruzione: 42`

Where in the comment you use Tua.
If a gender specific word is needed, it's possible to do so, like we do [here](https://github.com/BigWigsMods/BigWigs/blob/dcd2bc30b5a6286e84f45122e60858224f545eda/Core/Locales/common.frFR.lua#L83)

**Comment by simoflorence** [comment]
I assure there's no need to gender specific translations in this contest; "Corruzione" is a female name in Italian but grammarly we use "Tua" (female) for both male and female reference

**Pull request merged**
