### PR TITLE
Locales: Add some esMX localization

### PR DESCRIPTION
**Pull request by brayanhenao**
Hi everyone, I added esMX localization for these modules:

- Azeroth
- Core
- Locales
- Plugins

I will start working on the other modules in the near future (Focused on the raid modules sorted by date of release of the raid)

### CODE REVIEW

**Comment by funkydude** [comment]
Thank you. Please do not bother translating the raids as they are about to be moved into a separate repository. I'll reply here with a link to the new repository when it is ready.

In regards to your current pull request: You created a separate file for Azeroth but you didn't translate anything in it. Why?

There's a typo in `Locales/esMx.lua ` it should be named with a capital X.

**Comment by brayanhenao** [comment]
@funkydude Thanks for the comments, I fixed them.

**Comment by funkydude** [comment]
Thanks for your work.
I didn't notice it at first, but in `BigWigs\Locales\esMX.lua` the entry `L.testNameplate` is partially in English. Probably because it was copied from `esES.lua`

**Comment by brayanhenao** [comment]
@funkydude I will create a PR fixing that, thanks!

**Comment by funkydude** [comment]
@brayanhenao BfA raid content is now available in it's new repository if you wish to translate it: https://github.com/BigWigsMods/BigWigs_BattleForAzeroth

**Pull request merged**
