### PR TITLE
Update koKR.lua

### PR DESCRIPTION
**Pull request by WetU**

### CODE REVIEW

**Comment by funkydude** [comment]
This is what I have so far but it needs numbers < 1 milion. AbbreviateLargeNumbers doesn't support that:
```
function AbbreviateNumber
	if asia then
		if n >= 100,000,000 then
			format "%.2f억" n/100000000
		elseif n >= 1,000,000 then
			format "%d만" n/10000
		elseif n >= 1,000 then
			--?
		else
			format "%d"
		end
	else
		if n >= 1,000,000,000 then
			format "%dB" n/1000000000
		elseif n >= 1,000,000 then
			format "%dM" n/1000000
		elseif n >= 1,000 then
			format "%dK" n/1000
		else
			format "%d"
		end
	end
end
```

**Comment by WetU** [comment]
function AbbreviateNumber
	if asia then
		if n >= 100,000,000 then
			format "%.2f억" n/100000000
		elseif n >= 10,000 then
			format "%.1f만" n/10000
		elseif n >= 1,000 then
  format "%d천" n/1000
		else
			format "%d"
		end
	else
...

This may be well functional.
Thanks your work.

**Comment by funkydude** [comment]
Use \` 3 times
type code
Use \` 3 times

```
code
```

**Comment by WetU** [comment]
Sorry, I wrote using mobile.
I will rewrite later using desktop.

**Comment by funkydude** [comment]
I fixed it already. Just wanted to let you know how to do it.

**Pull request closed without merging**
