### PR TITLE
Add antorus cutscenes

### PR DESCRIPTION
**Pull request by cexikitin**
https://github.com/BigWigsMods/BigWigs/issues/400

### CODE REVIEW

**Comment by cexikitin** [comment]
@nebularg anything preventing this from getting merged?

**Comment by Justw8** [comment]
We`re testing/checking it first before merging!

**Comment by funkydude** [comment]
Rename "stuff" to "portal"

**Comment by cexikitin** [comment]
Changed stuff to portal, added some context.

**Comment by cexikitin** [comment]
and didn't notice the caps whoops

**Pull request merged**
