### PR TITLE
zhCN/zhTW update

### PR DESCRIPTION
**Pull request by adavak**
zhCN/zhTW update.

### CODE REVIEW

**Comment by funkydude** [comment]
This is the exact same as #14, why did you create a new PR?

**Comment by adavak** [comment]
.....i only create one. why have two pull request. something mess me up.

**Comment by funkydude** [comment]
You haven't resolved the original point I brought up.

**Comment by adavak** [comment]
I closed #14 and you guide the original point is "new align translations?"
I checked.

**Comment by funkydude** [comment]
Translate these in the same pull request:
https://github.com/BigWigsMods/BigWigs/blob/master/Plugins/Locales/zhCN.lua#L9

**Pull request closed without merging**
