### PR TITLE
PT-BR Translation

### PR DESCRIPTION
**Pull request by rogeriocamorim**
Here is my contribution to the project.

### CODE REVIEW

**Comment by funkydude** [comment]
You need to remove `--` for the new translation to load

**Comment by rogeriocamorim** [comment]
> You need to remove `--` for the new translation to load

On those?
--L.adds_spawning

**Comment by funkydude** [comment]
Yup! But only in front of the actual translations. So:
`--L.wave_count = "Wave %d of %d" -- Wave 1 of 3 (Usually waves of adds)`
becomes
`L.wave_count = "Wave %d of %d" -- Wave 1 of 3 (Usually waves of adds)`

(Don't remove the one that's in front of the descriptive text)

**Comment by funkydude** [comment]
Superseded by #1876

**Pull request closed without merging**
