### PR TITLE
deDE Update

### PR DESCRIPTION
**Pull request by Dynaletik**
Commented out identical locales.

### CODE REVIEW

**Comment by funkydude** [comment]
There's no need to comment out identical locales. It makes it seem like it's not been reviewed.

**Comment by Dynaletik** [comment]
Okay I thought performance-wise this would perhaps be better. Will edit.

**Comment by funkydude** [comment]
Nope, it has no effect on performance at all

**Comment by Dynaletik** [comment]
Okay. Thanks for info. Updated. :)

**Pull request merged**
