### PR TITLE
verify Challenge Mode isn't active when toggling logging

### PR DESCRIPTION
**Pull request by ljosberinn**
- fixes https://github.com/BigWigsMods/BigWigs/issues/1330
- issues soon celebrating 2nd birthday so I figured I might aswell

### CODE REVIEW

**Comment by funkydude** [comment]
Does it stop logging after defeating the final boss?

**Comment by ljosberinn** [comment]
No, after the first boss

**Comment by funkydude** [comment]
I'm talking about with your change, not what the current issue is.

**Comment by ljosberinn** [comment]
Right, unsure, doubt the event order is ENCOUNTER_END before CHALLENGE_MODE_END. A separate listener that watches CHALLENGE_MODE_END would be better suited. A zone-based approach using GetDifficutlyInfo would be better for dungons in general however.

**Comment by funkydude** [comment]
When submitting a PR, there's a general expectation that you've tested the code. If you don't know if logging stops after the last boss, then what scenario are you expecting to end logging?

**Comment by funkydude** [comment]
PRs are a trust based relationship. We trust that you are operating in good faith. Comparing that to your disappointment and expectation of a bug fix is strange. 

Regardless, when questioned on that trust, instead of providing reassurance, you decided to have a rant. So I think that's the end of this, as I don't see how we can realistically trust any changes you submit.

**Pull request closed without merging**
