### PR TITLE
frFR Update

### PR DESCRIPTION
**Pull request by tborlee**

### CODE REVIEW

**Comment by funkydude** [comment]
`L.link_with = "Lié(e) avec %s"`
Unrelated to your changes, but can you explain why the `(e)` is necessary?

**Comment by tborlee** [comment]
If the player is male, it is “Lié avec”
If the player is female, it is “Liée avec”
So I use the french convention “Lié(e) avec” to represent both.

I might change that to “Lié•e avec” later, since it is a more modern approach and cleaner.

**Comment by tborlee** [comment]
Well the first examples that come to my mind are these ones for AutoReply.lua for "I'm busy in combat with":

```
L.autoReplyBasic = "Je suis occupé à combattre un boss."
L.autoReplyNormal = "Je suis occupé à combattre '%s'."
L.autoReplyAdvanced = "Je suis occupé à combattre '%s' (%s). %d/%d joueurs en vie."
L.autoReplyExtreme = "Je suis occupé à combattre '%s' (%s). %d/%d joueurs en vie : %s"
``` 
It is currently not gender-neutral, so I should change them to that:

```
L.autoReplyBasic = "Je suis occupé(e) à combattre un boss."
L.autoReplyNormal = "Je suis occupé(e) à combattre '%s'."
L.autoReplyAdvanced = "Je suis occupé(e) à combattre '%s' (%s). %d/%d joueurs en vie."
L.autoReplyExtreme = "Je suis occupé(e) à combattre '%s' (%s). %d/%d joueurs en vie : %s"
```

A solution would be to use a different phrasing that doesn't need that kind of tricks, e.g. instead of translating directly "I'm busy in combat with...", I could use instead "I'm currently in combat against/with...", which will be translated in a gender-neutral way like this:

```
L.autoReplyBasic = "Je suis actuellement en combat contre un boss."
L.autoReplyNormal = "Je suis actuellement en combat contre '%s'."
L.autoReplyAdvanced = "Je suis actuellement en combat contre %s' (%s). %d/%d joueurs en vie."
L.autoReplyExtreme = "Je suis actuellement en combat contre '%s' (%s). %d/%d joueurs en vie : %s"
```
Not always possible, and sometime difficult, but I can try to improve my translations to be more gender-neutral without needing to use 2 separate strings.

**Comment by funkydude** [comment]
I was thinking about solutions for language that refers to a player in your raid. I don't think I'd go as far as to try and compensate for language that refers to the gender of a boss unfortunately, we'd need a list for every single boss and even then, the gender of some bosses would be up for debate as I doubt the `UnitSex` API would be reliable for NPCs.

Unless I've completely misunderstood and the whisper is actually the gender of the person sending the whisper?

**Comment by tborlee** [comment]
Yes indeed, the whisper is actually the gender of the person sending the whisper

**Comment by tborlee** [comment]
Speaking of genders, just in case you are not aware, since Legion (I think), regular NPC can have different names according to their gender.

For example, for the Kirin Tor Guardian: https://www.wowhead.com/npc=104091/kirin-tor-guardian

In French, they are call "Gardien du Kirin Tor" (male) and "Gardienne du Kirin Tor" (female).

Not an issue for bosses of course, but it might cause trouble for trash mobs for example if the module relies on the translated name.

**Comment by funkydude** [comment]
Is this also true for the linked message? i.e. it's your gender not the gender you're linked with?

If that's the case then this is super easy to fix.
`"I am a ".. (UnitSex("player") == 2 and "male" or "female") .." player."`

**Comment by funkydude** [comment]
> Not an issue for bosses of course, but it might cause trouble for trash mobs for example if the module relies on the translated names.

Nothing in BigWigs relies on translated trash names these days. The only place we use it is in the GUI for trash modules, and it only serves as a header/separator. Whichever gender is used is irrelevant there, as trash mobs typically contain multiple genders anyway.

**Comment by tborlee** [comment]
> Is this also true for the linked message? i.e. it's your gender not the gender you're linked with?

Yes you are correct, we use the gender of the person performing the action in this case.

e.g. if I'm female and linked to someone male, I would say "Je suis liée" and he would said "Je suis lié".
However, speaking of him (aka you), I would say "tu es lié" and he would said speaking of me "tu es liée".

Sorry if it is not clear, it is difficult to explain something like that in an another language.

> > Not an issue for bosses of course, but it might cause trouble for trash mobs for example if the module relies on the translated names.
> 
> Nothing in BigWigs relies on translated trash names these days. The only place we use it is in the GUI for trash modules, and it only serves as a header/separator. Whichever gender is used is irrelevant there, as trash mobs typically contain multiple genders anyway.

You are right, I will not miss those times where everything was parsed from the combat log.

**Comment by funkydude** [comment]
This should now be fixed for the linked message.

**Pull request merged**
