### PR TITLE
Add AutoReply feature/plugin

### PR DESCRIPTION
**Pull request by funkydude**
WIP

### CODE REVIEW

**Comment by elvador** [comment]
Should use the health pool data form the Statistics plugin imo.

**Comment by Zireael-N** [comment]
I'm of the opinion that it should be a "I'm busy, do not disturb"-feature rather than some sort of telemetry sending "I'm fighting X boss on Y difficulty, X/Y people are alive, boss is at X% HP, by the way". If anything, I'd prefer an option to exclude the encounter's name as well.

**Comment by elvador** [comment]
You can just set your status as DND, you don't need an addon of that.

But I guess we could just have an option for both ("Privacy mode"/"Telemetry mode").
For me personally if I get an automatic response, I'd like to have it include the boss hp as well. This will of course never be perfect (different Phases, Bosses healing, etc), but it's the same as the stats plugin: Better than nothing.

Aside from that: Should it be on per default? Not sure about that.

**Comment by Justw8** [comment]
Options I'm seeing as viable, and perhaps all could be implemented with a dropdown to select how you want your whispers to respond:

1) No reply whisper
2) Reply combat status only, 'I'm currently in boss combat'
3) Reply combat status with encounter name, 'I'm currently in boss combat with XYZ'
4) Reply combat status with encounter info (boss%),  'I'm currently in boss combat with XYZ (health%)'

In addition to this:
5) Notify when combat ends

**Comment by Zireael-N** [comment]
> You can just set your status as DND, you don't need an addon of that.

You can, but an addon does that for you. :P

Justwait's suggestion is the way to go, IMO.

**Comment by funkydude** [comment]
Last call

**Comment by Stanzilla** [comment]
The answer messages are super weird, who talks like that? :E

Suggestions:

```
L.autoReplyBasic = "I'm busy fighting a boss encounter."
L.autoReplyNormal = "I'm busy fighting '%s'."
L.autoReplyAdvanced = "I'm busy fighting '%s' (%s) with %d/%d people alive."
L.autoReplyExtreme = "I'm busy fighting '%s' (%s) with %d/%d people alive: %s"

L.autoReplyLeftCombatBasic = "I'm no longer in combat with a boss encounter."
L.autoReplyLeftCombatNormalWin = "I just killed '%s'."
L.autoReplyLeftCombatNormalWipe = "I just wiped on '%s'."
L.autoReplyLeftCombatAdvancedWin = "I just killed '%s' with %d/%d people alive."
L.autoReplyLeftCombatAdvancedWipe = "I wiped on '%s' at: %s"
```

**Comment by Zireael-N** [comment]
> I just killed 'Eonar'.

:thinking:

**Comment by Stanzilla** [comment]
okay okay, `defeated`

**Comment by Stanzilla** [comment]
@funkydude are you open to changing this or nah? Could do a PR if you agree.

**Pull request merged**
