### PR TITLE
Opal Crush sound

### PR DESCRIPTION
**Pull request by 4ydan**
Added missing sound info to "The Primal Council" encounter.

### CODE REVIEW

**Comment by 4ydan** [comment]
image

**Comment by 4ydan** [comment]
image

**Comment by 4ydan** [comment]
Copied the Id from ThePrimalCouncil.lua
image

**Comment by nebularg** [comment]
You were editing an autogenerated file :p thanks for reminding us about this, though

**Comment by funkydude** [comment]
Editing the options file does nothing, it's automatically generated when the zip is created.
Adding audio needs to be done in the boss module itself.
e.g.
`self:PlaySound(args.spellId, "info")`

**Comment by 4ydan** [comment]
unlucky, but ty, I have no clue about the repo

**Pull request closed without merging**
