### PR TITLE
Update icon usage of Sasszine

### PR DESCRIPTION
**Pull request by alivedise**
Not sure why, but when in Sasszine battle heroic mode, the icon will constant change - not always use 3 specific icons but change between 4 icons. Would be good if the icon is fixed.

### CODE REVIEW

**Comment by elvador** [comment]
This is already fixed by sorting the `iconsUnused` table: https://github.com/alivedise/BigWigs/blob/f4f769be3d56935c66207d96c679668f38de551a/TombOfSargeras/Sasszine.lua#L172

On why this happens: With `tDeleteItem` and `table.insert` the list behaves like a queue, so after 3 marks, the table will be {4, 1, 2, 3}. Sorting it solves this problem.

**Comment by alivedise** [comment]
Cool thx

**Comment by alivedise** [comment]
BTW, is there a reason not to rest iconsUnused to {1,2,3,4} on each Hydrashot is invoked, but rather maintain the list upon HydrashotRemoved? Sort is consuming computation power.

**Comment by elvador** [comment]
Sorting 4 values is not consuming any computation power.

**Comment by galedric** [comment]
Why not simply use `#list` as the icon?

**Pull request closed without merging**
