### PR TITLE
Core: Add Dungeon ID's to Loader

### PR DESCRIPTION
**Pull request by Avyiel**
This PR aims to add support for all Classic dungeons to be loaded.

### CODE REVIEW

**Comment by nebularg** [comment]
So these need to be the instance id (from GetInstanceInfo), you can pull them from https://wow.tools/dbc/?dbc=map&build=1.13.4.34835

**Comment by Avyiel** [comment]
> So these need to be the instance id (from GetInstanceInfo), you can pull them from https://wow.tools/dbc/?dbc=map&build=1.13.4.34835

Would [these](https://wow.gamepedia.com/InstanceID) work as well? WoW.tools refuses to load any results for me.

**Comment by nebularg** [comment]
Talking about the same thing in two place, lol. Yea, should be fine for except for all of Scarlet Monastery being 189

**Comment by Avyiel** [comment]
> Talking about the same thing in two place, lol. Yea, should be fine for except for all of Scarlet Monastery being 189

You got all ID's memorised or something?! Damn dude! Well, thanks! Got everything right now

**Comment by nebularg** [comment]
6052889b5

**Pull request closed without merging**
