### PR TITLE
Update ruRU.lua

### PR DESCRIPTION
**Pull request by mone-ennen**
Add translations for Hungering Destroyer / Stone Legion Generals / Sire Denathrius

### CODE REVIEW

**Comment by funkydude** [comment]
@mone-ennen Thanks!
`L.add_spawn = "Алые кабалисты откликнулись на призыв Денатрия."`
Are you aware this isn't a translation? It's an in-game trigger, it needs to match the in-game text exactly.

@Wetxius Are you ok with these changes?

**Comment by mone-ennen** [comment]
@funkydude Yes, I took the text from our kill video: https://youtu.be/133_MiDkeNQ?t=208 (at 3:28 timestamp)

**Comment by Wetxius** [comment]
I don't raiding, but according to video it's correct.

**Comment by funkydude** [comment]
Thank you both!

**Pull request merged**
