### PR TITLE
Update koKR.lua

### PR DESCRIPTION
**Pull request by WetU**

### CODE REVIEW

**Comment by funkydude** [comment]
Why are you not using `백만`?

**Comment by WetU** [comment]
백만 is not a number unit in Korean.
Also has no number unit that meaning million.
As far as I know, zhCN & zhTW & koKR 3 languages are different only in number units.

**Comment by elvador** [comment]
Using 10000 as divisor would result in a very large value which is too big for the InfoBox. 
Can you please run `/dump SECOND_NUMBER_CAP_NO_SPACE` in a koKR client and tell us the value of it?

**Comment by WetU** [comment]
SECOND_NUMBER_CAP_NO_SPACE="억"

NUMBER_ABBREVIATION_DATA={
  [1]={
    breakpoint=1000000000,
    significandDivisor=10000000,
    abbreviation="억",
    fractionDivisor=1
  },
  [2]={
    breakpoint=10000000,
    significandDivisor=1000000,
    abbreviation="억",
    fractionDivisor=10
  },
  [3]={
    breakpoint=10000,
    significandDivisor=1000,
    abbreviation="만",
    fractionDivisor=10
  }
}

**Pull request merged**
